[package]
name = "mgi"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rand = "0.8.5"

[dependencies]
mgics = { path = "../mgics/" }
sdl2 = { version = "0.35.2", features = ["ttf", "image", "unsafe_textures"] }
